"""
Twilio WhatsApp service.
Only fires for HIGH severity alerts.
Messages are generated by the Advisor Agent in the user's language.
"""
from twilio.rest import Client
from config import settings
import logging

logger = logging.getLogger(__name__)

_twilio_client: Client | None = None


def get_twilio_client() -> Client:
    global _twilio_client
    if _twilio_client is None:
        _twilio_client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
    return _twilio_client


def send_whatsapp_alert(to_number: str, message: str) -> str:
    """
    Send a WhatsApp message via Twilio sandbox.
    to_number: E.164 format, e.g. +919876543210
    Returns Twilio message SID on success.
    """
    if not to_number.startswith("+"):
        to_number = f"+{to_number}"

    client = get_twilio_client()
    msg = client.messages.create(
        from_=settings.TWILIO_WHATSAPP_FROM,
        to=f"whatsapp:{to_number}",
        body=message,
    )
    logger.info(f"WhatsApp sent to {to_number}, SID={msg.sid}")
    return msg.sid


def format_whatsapp_message(
    alert_type: str,
    title: str,
    message: str,
    business_name: str,
) -> str:
    """
    Format a clean WhatsApp message string.
    message is already in the user's language from the Advisor Agent.
    """
    emoji_map = {
        "underpricing": "💰",
        "stock_depletion": "📦",
        "scheme_deadline": "📋",
        "sales_anomaly": "📊",
    }
    emoji = emoji_map.get(alert_type, "⚠️")
    return (
        f"{emoji} *Bizpanion Alert — {business_name}*\n\n"
        f"{message}\n\n"
        f"_Open the Bizpanion app for full details and recommended action._"
    )
